name: owasp-dep-check
on: [push]

jobs:
  depcheck:
    name: Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'bodgeit'
          path: '.'
          format: 'SARIF'
          args: >
            --failOnCVSS 7
            --enableRetired
      - name: Upload SARIF to github
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: reports/dependency-check-report.sarif
        if: always()
